name: taxi_app
description: Multi-role taxi booking MVP (User, Driver, Admin).
publish_to: "none"
version: 1.0.9+15

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.1.6
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  google_sign_in: ^6.2.1
  http: ^1.2.2
  uuid: ^4.5.1
  intl: ^0.19.0
  flutter_polyline_points: ^2.1.0
  url_launcher: ^6.3.2
  dotlottie_loader: ^0.0.6
  lottie: ^3.3.1
  webview_flutter: ^4.13.1
  shared_preferences: ^2.5.3
  package_info_plus: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/vehicles/
    - assets/animations/
    - hosting/
    - shorebird.yaml
